package site

import (
	"bytes"
	"fmt"
	"html/template"
	"strings"

	chromahtml "github.com/alecthomas/chroma/v2/formatters/html"
	"github.com/alecthomas/chroma/v2/styles"
	"github.com/yuin/goldmark"
	highlighting "github.com/yuin/goldmark-highlighting/v2"
	"github.com/yuin/goldmark/ast"
	"github.com/yuin/goldmark/extension"
	"github.com/yuin/goldmark/parser"
	"github.com/yuin/goldmark/text"
)

// chromaStyle is the single source of truth for the code-highlighting theme;
// the matching CSS is generated by chromaCSS.
const chromaStyle = "github"

func newMarkdown() goldmark.Markdown {
	return goldmark.New(
		goldmark.WithExtensions(
			extension.GFM,
			highlighting.NewHighlighting(
				highlighting.WithStyle(chromaStyle),
				highlighting.WithFormatOptions(chromahtml.WithClasses(true)),
			),
		),
		goldmark.WithParserOptions(parser.WithAutoHeadingID()),
	)
}

// render turns markdown into sanitised-by-construction HTML plus a table of
// contents built from the heading IDs goldmark assigns.
func render(md goldmark.Markdown, source string) (template.HTML, []TOCEntry, error) {
	src := []byte(source)
	doc := md.Parser().Parse(text.NewReader(src))
	toc := extractTOC(doc, src)

	var buf bytes.Buffer
	if err := md.Renderer().Render(&buf, src, doc); err != nil {
		return "", nil, fmt.Errorf("failed to render markdown: %w", err)
	}
	return template.HTML(buf.String()), toc, nil
}

// extractTOC collects depth-2 headings, nesting depth-3 headings under the
// preceding depth-2 entry.
func extractTOC(doc ast.Node, source []byte) []TOCEntry {
	var toc []TOCEntry
	ast.Walk(doc, func(n ast.Node, entering bool) (ast.WalkStatus, error) {
		if !entering {
			return ast.WalkContinue, nil
		}
		h, ok := n.(*ast.Heading)
		if !ok || (h.Level != 2 && h.Level != 3) {
			return ast.WalkContinue, nil
		}

		entry := TOCEntry{Title: nodeText(h, source), Anchor: headingID(h)}
		if h.Level == 3 && len(toc) > 0 {
			parent := &toc[len(toc)-1]
			parent.Children = append(parent.Children, entry)
		} else {
			toc = append(toc, entry)
		}
		return ast.WalkSkipChildren, nil
	})
	return toc
}

func headingID(n ast.Node) string {
	if v, ok := n.AttributeString("id"); ok {
		switch id := v.(type) {
		case []byte:
			return string(id)
		case string:
			return id
		}
	}
	return ""
}

func nodeText(n ast.Node, source []byte) string {
	var b strings.Builder
	ast.Walk(n, func(c ast.Node, entering bool) (ast.WalkStatus, error) {
		if entering {
			if t, ok := c.(*ast.Text); ok {
				b.Write(t.Segment.Value(source))
			}
		}
		return ast.WalkContinue, nil
	})
	return b.String()
}

// chromaCSS generates the stylesheet for the highlighted code spans.
func chromaCSS() ([]byte, error) {
	style := styles.Get(chromaStyle)
	if style == nil {
		style = styles.Fallback
	}
	var buf bytes.Buffer
	if err := chromahtml.New(chromahtml.WithClasses(true)).WriteCSS(&buf, style); err != nil {
		return nil, fmt.Errorf("failed to generate chroma css: %w", err)
	}
	return buf.Bytes(), nil
}
